# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='content',
        ),
    ]
