# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_remove_invitation_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
